# Generated by Django 2.2.6 on 2019-11-08 02:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terreno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='Terrenos')),
                ('direccion', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=200)),
                ('precio', models.DecimalField(decimal_places=3, max_digits=19)),
                ('metros_2', models.DecimalField(decimal_places=3, max_digits=19)),
                ('tipo_contacto', models.CharField(choices=[('V', 'Venta'), ('C', 'Compra')], max_length=1)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cliente')),
            ],
            options={
                'verbose_name': 'Terreno',
                'verbose_name_plural': 'Terrenos',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='Departamentos')),
                ('direccion', models.CharField(max_length=200)),
                ('num_piso', models.IntegerField(max_length=2)),
                ('ciudad', models.CharField(max_length=200)),
                ('precio', models.DecimalField(decimal_places=3, max_digits=19)),
                ('cant_habitaciones', models.IntegerField()),
                ('cant_baños', models.IntegerField()),
                ('metros_2', models.DecimalField(decimal_places=3, max_digits=19)),
                ('tipo_contacto', models.CharField(choices=[('V', 'Venta'), ('C', 'Compra')], max_length=1)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cliente')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ['-created_date'],
            },
        ),
    ]
