# Generated by Django 2.2.6 on 2019-11-08 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_departamento_terreno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casa',
            name='tipo_contacto',
            field=models.CharField(choices=[('Venta', 'Venta'), ('Compra', 'Compra')], max_length=1),
        ),
    ]
