# Generated by Django 2.2.6 on 2019-11-08 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191108_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casa',
            name='metros_2',
            field=models.DecimalField(decimal_places=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='casa',
            name='precio',
            field=models.DecimalField(decimal_places=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='metros_2',
            field=models.DecimalField(decimal_places=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='precio',
            field=models.DecimalField(decimal_places=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='terreno',
            name='metros_2',
            field=models.DecimalField(decimal_places=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='terreno',
            name='precio',
            field=models.DecimalField(decimal_places=0, max_digits=19),
        ),
    ]
