# Generated by Django 2.2.6 on 2019-11-08 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20191108_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='casa',
            name='destacado',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='departamento',
            name='destacado',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='terreno',
            name='destacado',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casa',
            name='tipo_contacto',
            field=models.CharField(choices=[('V', 'Venta'), ('C', 'Compra')], max_length=10),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='tipo_contacto',
            field=models.CharField(choices=[('V', 'Venta'), ('C', 'Compra')], max_length=10),
        ),
        migrations.AlterField(
            model_name='terreno',
            name='tipo_contacto',
            field=models.CharField(choices=[('V', 'Venta'), ('C', 'Compra')], max_length=10),
        ),
    ]
