# Generated by Django 2.2.6 on 2019-11-08 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20191108_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casa',
            name='tipo_contacto',
            field=models.CharField(choices=[('Venta', 'Venta'), ('Arriendo', 'Arriendo')], max_length=10),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='tipo_contacto',
            field=models.CharField(choices=[('Venta', 'Venta'), ('Arriendo', 'Arriendo')], max_length=10),
        ),
        migrations.AlterField(
            model_name='terreno',
            name='tipo_contacto',
            field=models.CharField(choices=[('Venta', 'Venta'), ('Arriendo', 'Arriendo')], max_length=10),
        ),
    ]
