# Generated by Django 2.2.6 on 2019-11-10 01:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20191108_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casa',
            name='published_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
