# Generated by Django 2.2.6 on 2019-11-10 23:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20191110_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terreno',
            name='published_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
