# Generated by Django 2.2.6 on 2019-11-13 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_galeria_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galeria',
            name='autor',
        ),
    ]
