# Generated by Django 2.2.6 on 2019-11-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_galeria_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeria',
            name='titulo',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
