# Generated by Django 2.2.6 on 2019-11-16 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_galeria_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='num_piso',
            field=models.IntegerField(),
        ),
    ]
