# Generated by Django 2.2.6 on 2019-11-16 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20191116_1728'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casa',
            options={'ordering': ['-created_date'], 'verbose_name': 'Casa', 'verbose_name_plural': 'Casas'},
        ),
    ]
